version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports: 
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub  
  firefox:  
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  smoke_test:
    image: skoar/project-alpha-suite
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=smoke_test.xml
    volumes:
      - ./smoke_test-result:/usr/share/trial/test-output
  regression_test:
    image: skoar/project-alpha-suite
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=regression_test.xml
    volumes:
      - ./regression_test-result:/usr/share/trial/test-output